### ISSUE TITLE
interactions -> hic_apps, client_app -> hic_app

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/msg_database#10]
client_app이라는건 의미적으로 모호하기에 rocon내의 terminology인 hic_app(human interactive client app)으로 변경합니다.

https://github.com/robotics-in-concert/msg_database/tree/master/msg_database_server/distro/client_apps

**Comment by eskim** [comment]
764e975483de84e0d5b56b22c29cd4ef96179765

**Comment by eskim** [comment]
80bfbcf0f3017c0182ac0231d760ef28e0a118a7

몇가지 추가로 rename 했습니다.
