### ISSUE TITLE
create rocon_app distro

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/msg_database#11]
hic_app과 같이 rocon_app repository를 적어놓은 yaml파일이 필요합니다.

e.g) distro/rocon_apps/rocon_apps.yaml

**Comment by jihoonl** [comment]
현재는 rapp_sync.js 내에 하드코딩되어있습니다.

https://github.com/robotics-in-concert/msg_database/blob/master/msg_database_server/rapp_sync.js#L22

추가적인 작업으로 환경변수를 통해 설정가능하면 좋겠습니다.

**Comment by eskim** [comment]
하드 코딩 되어 있는 URL 의 내용을 살펴보면, 특별한 형식 없이
한줄에 한 URL로 작성되어 있습니다. (각 URL은 rapp tar.gz 파일의 URL)

yaml 로 형식을 변경되었으면 하는 거죠?

**Comment by jihoonl** [comment]
네 맞습니다. 이후에 추가적인 정보들을 넣을 수 있기에 yaml형식으로 하는게 좋을꺼 같습니다.

**Comment by eskim** [comment]
rocon_apps_distro 라는 branch 에 msg_database_server/distro/rocon_apps 라는 폴더와 그 밑에 파일을 만들었는데 한번 살펴봐 주세요.

어떻게 생각하시나요?

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/msg_database/tree/rocon_apps_distro/msg_database_server/distro/rocon_apps

**Comment by jihoonl** [comment]
넵 좋은거 같습니다. 이후에 description이라던가 다른 포맷 추가지원을 생각해볼수도 있겠지만 지금상황에선 가장 옳은 방법인거 같습니다.

**Comment by eskim** [comment]
#17  merge 하겠습니다.

**Comment by jihoonl** [comment]
:+1:
