### ISSUE TITLE
rename env variables

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/msg_database#12]
새로 변경되는 repository와 package이름에 맞춰서 재구성되어야합니다.

**Comment by jihoonl** [comment]
현재 확인된 환경변수로는

* [MSG_DATABASE_MONGO_URL](https://github.com/robotics-in-concert/msg_database/blob/master/msg_database_server/index.js#L14)
* [MSG_DATABASE_MONGO_PORT](https://github.com/robotics-in-concert/msg_database/blob/master/msg_database_server/index.js#L23)

들이 있고

#11과 #13이후에 추가적인 환경변수가 있습니다.

**Comment by eskim** [comment]
f1cbcde2021bf2fb134383fe92fa313056902e4d 수정완료.
