### ISSUE TITLE
configurable hic_app distro

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/msg_database#13]
현재 임시장소로 하드코딩되어있습니다.

https://github.com/robotics-in-concert/msg_database/blob/master/msg_database_server/client_apps_sync.js#L9

#11에 설명한 것처럼 환경변수로 설정가능하면 좋겠습니다.

**Comment by eskim** [comment]
환경변수로 

* `ROCON_PROTOCOLS_WEB_HIC_APPS_URL` : hic_apps yaml 의 url
* `ROCON_PROTOCOLS_WEB_ROCON_APPS_URL` : rocon_apps yaml 의 url

이렇게 생각하고 있는데 어떠신지요?

**Comment by jihoonl** [comment]
넵 :+1:

**Comment by eskim** [comment]
8ad35e6675961749615f4f3b05c2bc9845890fa0 - rocon apps 부분 먼저 작업했습니다. 환경변수 설정이 되어 있지 않은때 예외 처리는 보너스 입니다.

**Comment by jihoonl** [comment]
음 이걸 default value를 하는건 어떨까요? 
default값은 현재 위치로 기록을 해놓고 만약에 env가 설정되어있으면 변경해서 사용가능하게 만들어서 메인은 open repository로 해놓고 사용자가 필요에 따라서 변경해서 쓸수있게하면 좋을꺼 같습니다.

**Comment by eskim** [comment]
02712041159390361a34f7aa199f0712f6ff6eab hic_apps yaml URL 로 수정후, 5be463239f12c72f61543b7719d236d42c12722f 환경 변수 처리 완료.

**Comment by eskim** [comment]
deafult value 로 현재 위치를 해놓는 것은 
현재 url 기반으로 fetch 해서 목록을 가져오는 로직으로 되어 있어 현재 위치(즉, local file system)를 별도로 처리하는 작업을 해야 하는 이슈가 있습니다.

별도의 이슈로 처리하는 것이 어떨가요?

**Comment by jihoonl** [comment]
새로운 이슈 만들었습니다.
